name = "smaster-192.168.64.19-8261"

master-addr = "0.0.0.0:8261"
advertise-addr = "192.168.64.19:8261"

peer-urls = "0.0.0.0:8291"
advertise-peer-urls="http://192.168.64.19:8291"

initial-cluster = "smaster-192.168.64.19-8261=http://192.168.64.19:8291"

log-level = "debug"
log-file = "./logs/dm-master1.log"
data-dir = "./data/dm-master1"
